# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
warnings_are_errors: false
cache: packages
bioc_packages: limma
after_success:
- Rscript -e 'covr::codecov()'
